Создана ветка rubber_array.
LyskaL/ORT_dz pull request #21
Opened 2016-11-17 13:59 UTC by LyskaL

Создать класс резинового массива, который умеет расширяться или сужаться
по необходимости.

2016-11-17 18:26 UTC, strazhkoe requested changes
Хорошо потестируй!

2016-11-17 18:26 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +	public void show() {
Удали этот метод. Вынеси вывод в main

2016-11-17 18:26 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +		if (index != -1) {
-1 вынеси в константу

2016-11-17 18:26 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +			int newSize = length() + (index-(array.length-1));
Может просто делать length*2? При добавлении в цикле по 1 элементу будет часто перераспределяться память

2016-11-20 11:51 UTC, strazhkoe requested changes

2016-11-20 11:51 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +		return array;
Do not do this! Возвращай копию

2016-11-20 11:51 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +		this.array[size++] = element;
А если выйдем за границу??

2016-11-20 12:48 UTC, strazhkoe requested changes

2016-11-20 12:48 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +			}
Думаю, что это надо делать в newSizeArray, так как это часть  расширения массива

2016-11-20 12:48 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +	}
Ты уменьшаешь размер массива после удаления данных из него?

2016-11-20 12:59 UTC, LyskaL commented
Да, размер уменьшается в методе remove.
Остальное сейчас исправлю.

20 Ноя 2016 г. 14:48 пользователь "Yevhen Strazhko" <
notifications@github.com> написал:

> *@strazhkoe* requested changes on this pull request.
> ------------------------------
>
> In src/rin2016/module8/rubber_array/Array.java
> <https://github.com/LyskaL/ORT_dz/pull/21#pullrequestreview-9363519>:
>
> > +		}
> +	}
> +	
> +	/*
> +	 * Добавляем элемент в массив (по индексу)
> +	 */
> +	public void add(final int element, final int index) {
> +		if (index > 0 && index <= size) {
> +			int sizeArray = array.length-1;
> +			if (index >= sizeArray) {
> +				int newSize = array.length * 2;
> +				newSizeArray(newSize);
> +			}
> +			for (int i = size; i >= index; i--) {
> +				this.array[i + 1] = array[i];
> +			}
>
> Думаю, что это надо делать в newSizeArray, так как это часть расширения
> массива
> ------------------------------
>
> In src/rin2016/module8/rubber_array/Array.java
> <https://github.com/LyskaL/ORT_dz/pull/21#pullrequestreview-9363519>:
>
> > +			int counter = 0;
> +			if (index != SEARCH_ERROR) {
> +				for (int i = index; i < size; i++) {
> +					if (array[i] == sArray[counter]) {
> +						counter++;
> +						int sIndex = findLastIndex(sArray, i, counter);
> +						if (sIndex != SEARCH_ERROR) {
> +							remove(i, sIndex);
> +							counter = 0;
> +							i--;
> +						}
> +					}
> +				}
> +			}
> +		}
> +	}
>
> Ты уменьшаешь размер массива после удаления данных из него?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/LyskaL/ORT_dz/pull/21#pullrequestreview-9363519>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AWGRGaSZ1R9NuK5ojORKNJNzl_RK-ybfks5rAEGigaJpZM4K1Vh6>
> .
>

2016-11-20 13:34 UTC, LyskaL commented
> +		}
+	}
+	
+	/*
+	 * Добавляем элемент в массив (по индексу)
+	 */
+	public void add(final int element, final int index) {
+		if (index > 0 && index <= size) {
+			int sizeArray = array.length-1;
+			if (index >= sizeArray) {
+				int newSize = array.length * 2;
+				newSizeArray(newSize);
+			}
+			for (int i = size; i >= index; i--) {
+				this.array[i + 1] = array[i];
+			}

Думаю, что это надо делать в newSizeArray, так как это часть расширения
массива


Но у меня этот метод (newSizeArray(newSize) работает немного по другому. Он
уменьшает размер массива или увеличивает в зависимости от размера. он не
знает index - элемента после которого нужно сдвигать элементы. Так же этот
метод (расширения массива) используется при конкатенации строк, а там
ничего сдвигать не нужно.

20 ноября 2016 г., 14:59 пользователь Lyuda Lyska <lucy.daehyun@gmail.com>
написал:

> Да, размер уменьшается в методе remove.
> Остальное сейчас исправлю.
>
> 20 Ноя 2016 г. 14:48 пользователь "Yevhen Strazhko" <
> notifications@github.com> написал:
>
> *@strazhkoe* requested changes on this pull request.
>> ------------------------------
>>
>> In src/rin2016/module8/rubber_array/Array.java
>> <https://github.com/LyskaL/ORT_dz/pull/21#pullrequestreview-9363519>:
>>
>> > +		}
>> +	}
>> +	
>> +	/*
>> +	 * Добавляем элемент в массив (по индексу)
>> +	 */
>> +	public void add(final int element, final int index) {
>> +		if (index > 0 && index <= size) {
>> +			int sizeArray = array.length-1;
>> +			if (index >= sizeArray) {
>> +				int newSize = array.length * 2;
>> +				newSizeArray(newSize);
>> +			}
>> +			for (int i = size; i >= index; i--) {
>> +				this.array[i + 1] = array[i];
>> +			}
>>
>> Думаю, что это надо делать в newSizeArray, так как это часть расширения
>> массива
>> ------------------------------
>>
>> In src/rin2016/module8/rubber_array/Array.java
>> <https://github.com/LyskaL/ORT_dz/pull/21#pullrequestreview-9363519>:
>>
>> > +			int counter = 0;
>> +			if (index != SEARCH_ERROR) {
>> +				for (int i = index; i < size; i++) {
>> +					if (array[i] == sArray[counter]) {
>> +						counter++;
>> +						int sIndex = findLastIndex(sArray, i, counter);
>> +						if (sIndex != SEARCH_ERROR) {
>> +							remove(i, sIndex);
>> +							counter = 0;
>> +							i--;
>> +						}
>> +					}
>> +				}
>> +			}
>> +		}
>> +	}
>>
>> Ты уменьшаешь размер массива после удаления данных из него?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/LyskaL/ORT_dz/pull/21#pullrequestreview-9363519>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/AWGRGaSZ1R9NuK5ojORKNJNzl_RK-ybfks5rAEGigaJpZM4K1Vh6>
>> .
>>
>

2016-11-23 21:09 UTC, strazhkoe requested changes

2016-11-23 21:09 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +			this.array[size++] = element;
It is too risky. You do not have bounds check here. Are you sure you would not have an array with length = 0?

2016-11-23 21:09 UTC, strazhkoe commented on src/rin2016/module8/rubber_array/Array.java
> +	private int[] copy(final int[] firstArray,
Please, rename your arguments to reflect their role in this method. Use such names as "from", "to" or "source", "destination"

2016-11-27 08:13 UTC, strazhkoe approved these changes

2016-11-27 08:13 UTC, merged