Создана ветка readers_of_library.
LyskaL/ORT_dz pull request #22
Opened 2016-11-19 01:44 UTC by LyskaL

Создан класс Reader - хранящий информацию о пользователи библиотеки:
ФИО, номер читательского билета, дата рождения, номер телефона и
факультет.

Создан класс ListReaders - хранящий информацию о читателях библиотеки. 

В программе реализованы методы:
- вывод данных о пользователе;
- вывод данных массива на экран;
- поиск (по фамилии) и вывод информации о читателях.

2016-11-19 01:45 UTC, LyskaL commented
В классе Reader нет проверки на валидности строк. 
Я с регулярными выражениями не дружу :( как сделать?

2016-11-20 12:22 UTC, strazhkoe commented
Подружиться с регулярными выражениями)) Хоть на базовом уровне

2016-11-20 12:40 UTC, strazhkoe requested changes

2016-11-20 12:40 UTC, strazhkoe commented on src/rin2016/module8/readers_of_library/ListReaders.java
> +					generateNumberOfLibraryCard();
Рекурсию убери. Есть потенциальная угроза переполнения стека, которая будет возникать "раз в год"

2016-11-20 12:40 UTC, strazhkoe commented on src/rin2016/module8/readers_of_library/Reader.java
> +	private void setBirthDate(final String birthDate) {
Можно применить класс GregorianCalendar https://docs.oracle.com/javase/7/docs/api/java/util/GregorianCalendar.html

2016-11-20 12:40 UTC, strazhkoe commented on src/rin2016/module8/readers_of_library/MainReaders.java
> +		// TODO если обратится в 3 элемент массива выдаст ошибку
Эта проблема исправлена?

2016-11-27 10:31 UTC, strazhkoe approved these changes

2016-11-27 10:31 UTC, merged