Создана ветка task11_29.
LyskaL/ORT_dz pull request #3
Opened 2016-11-02 17:26 UTC by LyskaL

a. Определить является ли сумма элементов массива четным числом?
b. Определить является ли сумма квадратов элементов массива пятизначным
числом.

2016-11-02 21:13 UTC, strazhkoe requested changes

2016-11-02 21:13 UTC, strazhkoe commented on src/rin2016/chapter11/Task11_29.java
> +		for(int i = 0; i < SIZE; i++) {
Тут и ниже используй array.length

2016-11-02 21:13 UTC, strazhkoe commented on src/rin2016/chapter11/Task11_29.java
> +		if((int)Math.log10(sumSquares)+1 == 5) {
значение 5 нужно вынести в константу

2016-11-05 20:52 UTC, strazhkoe commented
А за пятерочку забыла?

2016-11-05 23:32 UTC, LyskaL commented
В константу вынесла, а в условии не изменила. Вот же...

2016-11-07 11:33 UTC, strazhkoe approved these changes

2016-11-07 11:34 UTC, merged